/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DbRouteImport } from './routes/db'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ImagesSplatRouteImport } from './routes/images/$'
import { Route as PostsIdRouteRouteImport } from './routes/posts/$id/route'
import { Route as PostsIdIndexRouteImport } from './routes/posts/$id/index'
import { Route as AdminPostsIndexRouteImport } from './routes/admin/posts/index'
import { Route as AdminMediaIndexRouteImport } from './routes/admin/media/index'
import { Route as PublicDatabaseIndexRouteImport } from './routes/_public/database/index'
import { Route as PostsIdEditRouteImport } from './routes/posts/$id/edit'
import { Route as AdminPostsNewRouteImport } from './routes/admin/posts/new'
import { Route as PublicPostSlugRouteImport } from './routes/_public/post/$slug'
import { Route as AdminPostsEditSlugRouteImport } from './routes/admin/posts/edit.$slug'

const DbRoute = DbRouteImport.update({
  id: '/db',
  path: '/db',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ImagesSplatRoute = ImagesSplatRouteImport.update({
  id: '/images/$',
  path: '/images/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIdRouteRoute = PostsIdRouteRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIdIndexRoute = PostsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsIdRouteRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMediaIndexRoute = AdminMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicDatabaseIndexRoute = PublicDatabaseIndexRouteImport.update({
  id: '/database/',
  path: '/database/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PostsIdEditRoute = PostsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PostsIdRouteRoute,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicPostSlugRoute = PublicPostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AdminPostsEditSlugRoute = AdminPostsEditSlugRouteImport.update({
  id: '/posts/edit/$slug',
  path: '/posts/edit/$slug',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/db': typeof DbRoute
  '/posts/$id': typeof PostsIdRouteRouteWithChildren
  '/images/$': typeof ImagesSplatRoute
  '/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/post/$slug': typeof PublicPostSlugRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/posts/$id/edit': typeof PostsIdEditRoute
  '/database': typeof PublicDatabaseIndexRoute
  '/admin/media': typeof AdminMediaIndexRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/posts/$id/': typeof PostsIdIndexRoute
  '/admin/posts/edit/$slug': typeof AdminPostsEditSlugRoute
}
export interface FileRoutesByTo {
  '/db': typeof DbRoute
  '/images/$': typeof ImagesSplatRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/post/$slug': typeof PublicPostSlugRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/posts/$id/edit': typeof PostsIdEditRoute
  '/database': typeof PublicDatabaseIndexRoute
  '/admin/media': typeof AdminMediaIndexRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/posts/$id': typeof PostsIdIndexRoute
  '/admin/posts/edit/$slug': typeof AdminPostsEditSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/db': typeof DbRoute
  '/posts/$id': typeof PostsIdRouteRouteWithChildren
  '/images/$': typeof ImagesSplatRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_public/post/$slug': typeof PublicPostSlugRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/posts/$id/edit': typeof PostsIdEditRoute
  '/_public/database/': typeof PublicDatabaseIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/posts/$id/': typeof PostsIdIndexRoute
  '/admin/posts/edit/$slug': typeof AdminPostsEditSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/db'
    | '/posts/$id'
    | '/images/$'
    | '/'
    | '/admin/'
    | '/post/$slug'
    | '/admin/posts/new'
    | '/posts/$id/edit'
    | '/database'
    | '/admin/media'
    | '/admin/posts'
    | '/posts/$id/'
    | '/admin/posts/edit/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/db'
    | '/images/$'
    | '/'
    | '/admin'
    | '/post/$slug'
    | '/admin/posts/new'
    | '/posts/$id/edit'
    | '/database'
    | '/admin/media'
    | '/admin/posts'
    | '/posts/$id'
    | '/admin/posts/edit/$slug'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/db'
    | '/posts/$id'
    | '/images/$'
    | '/_public/'
    | '/admin/'
    | '/_public/post/$slug'
    | '/admin/posts/new'
    | '/posts/$id/edit'
    | '/_public/database/'
    | '/admin/media/'
    | '/admin/posts/'
    | '/posts/$id/'
    | '/admin/posts/edit/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DbRoute: typeof DbRoute
  PostsIdRouteRoute: typeof PostsIdRouteRouteWithChildren
  ImagesSplatRoute: typeof ImagesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/db': {
      id: '/db'
      path: '/db'
      fullPath: '/db'
      preLoaderRoute: typeof DbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/images/$': {
      id: '/images/$'
      path: '/images/$'
      fullPath: '/images/$'
      preLoaderRoute: typeof ImagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$id/': {
      id: '/posts/$id/'
      path: '/'
      fullPath: '/posts/$id/'
      preLoaderRoute: typeof PostsIdIndexRouteImport
      parentRoute: typeof PostsIdRouteRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/media/': {
      id: '/admin/media/'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/database/': {
      id: '/_public/database/'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof PublicDatabaseIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/posts/$id/edit': {
      id: '/posts/$id/edit'
      path: '/edit'
      fullPath: '/posts/$id/edit'
      preLoaderRoute: typeof PostsIdEditRouteImport
      parentRoute: typeof PostsIdRouteRoute
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/posts/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/post/$slug': {
      id: '/_public/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof PublicPostSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/admin/posts/edit/$slug': {
      id: '/admin/posts/edit/$slug'
      path: '/posts/edit/$slug'
      fullPath: '/admin/posts/edit/$slug'
      preLoaderRoute: typeof AdminPostsEditSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicPostSlugRoute: typeof PublicPostSlugRoute
  PublicDatabaseIndexRoute: typeof PublicDatabaseIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicPostSlugRoute: PublicPostSlugRoute,
  PublicDatabaseIndexRoute: PublicDatabaseIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPostsNewRoute: typeof AdminPostsNewRoute
  AdminMediaIndexRoute: typeof AdminMediaIndexRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
  AdminPostsEditSlugRoute: typeof AdminPostsEditSlugRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminPostsNewRoute: AdminPostsNewRoute,
  AdminMediaIndexRoute: AdminMediaIndexRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
  AdminPostsEditSlugRoute: AdminPostsEditSlugRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface PostsIdRouteRouteChildren {
  PostsIdEditRoute: typeof PostsIdEditRoute
  PostsIdIndexRoute: typeof PostsIdIndexRoute
}

const PostsIdRouteRouteChildren: PostsIdRouteRouteChildren = {
  PostsIdEditRoute: PostsIdEditRoute,
  PostsIdIndexRoute: PostsIdIndexRoute,
}

const PostsIdRouteRouteWithChildren = PostsIdRouteRoute._addFileChildren(
  PostsIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DbRoute: DbRoute,
  PostsIdRouteRoute: PostsIdRouteRouteWithChildren,
  ImagesSplatRoute: ImagesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
