/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DbRouteImport } from './routes/db'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostIdRouteImport } from './routes/post/$id'
import { Route as ImagesSplatRouteImport } from './routes/images/$'
import { Route as PostsIdRouteRouteImport } from './routes/posts/$id/route'
import { Route as PostsIdIndexRouteImport } from './routes/posts/$id/index'
import { Route as PostsIdEditRouteImport } from './routes/posts/$id/edit'

const DbRoute = DbRouteImport.update({
  id: '/db',
  path: '/db',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIdRoute = PostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesSplatRoute = ImagesSplatRouteImport.update({
  id: '/images/$',
  path: '/images/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIdRouteRoute = PostsIdRouteRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIdIndexRoute = PostsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsIdRouteRoute,
} as any)
const PostsIdEditRoute = PostsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PostsIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/db': typeof DbRoute
  '/posts/$id': typeof PostsIdRouteRouteWithChildren
  '/images/$': typeof ImagesSplatRoute
  '/post/$id': typeof PostIdRoute
  '/posts/$id/edit': typeof PostsIdEditRoute
  '/posts/$id/': typeof PostsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/db': typeof DbRoute
  '/images/$': typeof ImagesSplatRoute
  '/post/$id': typeof PostIdRoute
  '/posts/$id/edit': typeof PostsIdEditRoute
  '/posts/$id': typeof PostsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/db': typeof DbRoute
  '/posts/$id': typeof PostsIdRouteRouteWithChildren
  '/images/$': typeof ImagesSplatRoute
  '/post/$id': typeof PostIdRoute
  '/posts/$id/edit': typeof PostsIdEditRoute
  '/posts/$id/': typeof PostsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/db'
    | '/posts/$id'
    | '/images/$'
    | '/post/$id'
    | '/posts/$id/edit'
    | '/posts/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/db' | '/images/$' | '/post/$id' | '/posts/$id/edit' | '/posts/$id'
  id:
    | '__root__'
    | '/'
    | '/db'
    | '/posts/$id'
    | '/images/$'
    | '/post/$id'
    | '/posts/$id/edit'
    | '/posts/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DbRoute: typeof DbRoute
  PostsIdRouteRoute: typeof PostsIdRouteRouteWithChildren
  ImagesSplatRoute: typeof ImagesSplatRoute
  PostIdRoute: typeof PostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/db': {
      id: '/db'
      path: '/db'
      fullPath: '/db'
      preLoaderRoute: typeof DbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$id': {
      id: '/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof PostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/$': {
      id: '/images/$'
      path: '/images/$'
      fullPath: '/images/$'
      preLoaderRoute: typeof ImagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$id/': {
      id: '/posts/$id/'
      path: '/'
      fullPath: '/posts/$id/'
      preLoaderRoute: typeof PostsIdIndexRouteImport
      parentRoute: typeof PostsIdRouteRoute
    }
    '/posts/$id/edit': {
      id: '/posts/$id/edit'
      path: '/edit'
      fullPath: '/posts/$id/edit'
      preLoaderRoute: typeof PostsIdEditRouteImport
      parentRoute: typeof PostsIdRouteRoute
    }
  }
}

interface PostsIdRouteRouteChildren {
  PostsIdEditRoute: typeof PostsIdEditRoute
  PostsIdIndexRoute: typeof PostsIdIndexRoute
}

const PostsIdRouteRouteChildren: PostsIdRouteRouteChildren = {
  PostsIdEditRoute: PostsIdEditRoute,
  PostsIdIndexRoute: PostsIdIndexRoute,
}

const PostsIdRouteRouteWithChildren = PostsIdRouteRoute._addFileChildren(
  PostsIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DbRoute: DbRoute,
  PostsIdRouteRoute: PostsIdRouteRouteWithChildren,
  ImagesSplatRoute: ImagesSplatRoute,
  PostIdRoute: PostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
